version: '3.8'

services:
  email-service:
    build: .
    command: python mvp/AI-Customer-Service/email_service.py
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./mvp/AI-Customer-Service:/app/mvp/AI-Customer-Service

  wechat-service:
    build: .
    command: python mvp/AI-Customer-Service/wechat_service.py
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./mvp/AI-Customer-Service:/app/mvp/AI-Customer-Service

  product-description:
    build: .
    command: python mvp/product-description/product_describer.py
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./mvp/product-description:/app/mvp/product-description